repos:
  - repo: https://github.com/timothycrosley/isort
    rev: "5.4.2"
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: flake8
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black