repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8